name: Linting Notebooks with Black

on:
  push:
    branches:
      - dev  # Change this to your repository's main branch
  pull_request:
    branches:
      - dev  
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"  # Change this to your desired Python version

    - name: Install dependencies
      run: |
        pip install black==23.1.0 nbformat black[jupyter]
      continue-on-error: false

    - name: Find notebooks
      id: find-notebooks
      run: |
        find . -name "*.ipynb" > notebooks.txt
      continue-on-error: true

    - name: Lint notebooks
      run: |
        cat notebooks.txt | xargs -I {} black --line-length 88 --check {}
      continue-on-error: true

    - name: Check lint results
      run: |
        if grep -q "would reformat" notebooks.txt; then
          echo "Linting issues found. Run 'black' to auto-format the notebooks."
          exit 1
        else
          echo "All notebooks are properly formatted."
        fi